# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100000)),
                ('create_time', models.DateField()),
                ('update_time', models.DateField()),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
